### PR TITLE
Issue #158   insertstyle node modules export docs

### PR DESCRIPTION
**Pull request by elycruz**
Cleans up docs related to using the `insert` feature.

Related to #157 and #158 .

### CODE REVIEW

**Comment by marcalexiei** [comment]
I opened #163 10 minutes ago. 
When you have time consider to take a look. 

It could solve the problem in a more "graceful" way 😄

**Comment by elycruz** [comment]
:-D, yeah I saw - I figured since I had updated the snippet I would added it for correctness/have it in the git history.

Started reviewing your PR though if we could get the required update on it's (apart from the prettier stuff) that would be better (as I don't get too much time for reviewing the PRs);  

Let's try to go for PRs/branches that build off each other (if necessary) - will allow for PR reviews to be completed faster.

**Comment by marcalexiei** [comment]
> Started reviewing your PR though if we could get the required update on it's (apart from the prettier stuff) that would be better

Prettier PR changes are nearly all related to code formatting, so they should't take long. 
In addition I highlighted some unrelated changes using review comments to speed up the review 🙂.

---

> if we could get the required update on it's (apart from the prettier stuff) that would be better

IMHO having a formatter and a linter (coming  🔜) ensure that the code is more readable and subject to errors,
so I consider prettier PR more important 😃

--- 

> (I don't get too much time for reviewing the PRs)

If you wish you can add me as collaborator with the triage permission:
_"Can read and clone this repository. Can also manage issues and pull requests"_ 

I can't edit or write any information related to the repository code and settings.
More info can be found [here](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role)

But with that permission at least I can at have CI checks running and avoid one review cycle just to fix some CI error 😅.

If you do not want to add me, no problem, I understand 😉.

**Comment by elycruz** [comment]
As to your previous comment, and adding you as 'triage' user, will look into it over the next coming days.

**Comment by marcalexiei** [comment]
Hi @elycruz, thanks for the invitation 🎉.
I see that you granted me the maintainer permission so I should be able to push to this repository 🙇.
However PRs require 1 approving review and I cannot approving my own PRs 😅.

If you don't have time to review the PR's,
I can turn around this by opening PRs just to check that the Cl is passing,
then cherry pick the commit(s) on `main`.

Let me know what is the most feasible solution for you!

Just a quick summary on the current 3 opened PR's if you have time to take a look:
1. #165 - very simple, just a fix for the coverage drop due to my earlier test changes
2. #163 - a more "clean" solution to avoid `node_modules` folder creation inside rollup output folder when using `insert` options (most of the changes are related to unit test)
3. #166 - support for sass modern compiler (it's very big but I would highly appreciate your feedback on it)

**Comment by elycruz** [comment]
@marcalexiei hey, I'm merging this one for now - you can still make the edit you require in your `insertStyle` PR.

**Comment by marcalexiei** [comment]
@elycruz beware that CI is failing due to format issues

**Comment by marcalexiei** [comment]
> you can still make the edit you require in your insertStyle PR.

`insertStyle` PR is ready from my point of view. 
Merging this PR now will probably cause conflict that I will have resolve on my branch.

**Pull request merged**
