### PR TITLE
Fix source map

### LINKED ISSUE #37: Support for sass source maps
I am currently generating the plugin like this

```
const sass = require('rollup-plugin-sass');
...
const output = 'my-output${env.prodution ? '.min' : ''}.css';
const sourceMap = `${output}.map`
const outputStyle = env.production ? 'compressed' : nested';
const plugin = sass({output, options: {sourceMap, outputStyle}});
```

Only the css file is generated. No css.map file is generated.

Is there something wrong with my config, or does the plugin not support source maps?

### PR DESCRIPTION
**Pull request by dishuostec**
Fixes #37

### CODE REVIEW

**Review by elycruz — CHANGES_REQUESTED** [review]
Code looks good but 3 tests fail:
```

  3 tests failed

  index » should support output as function

  C:\Users\elydelac\workspace\elycruz\rollup-plugin-sass\test\index.js:144

   143:   t.is(squash(readFileSync(outputOptions.file).toString()), '');
   144:   t.true(outputSpy.calledWith(squash(`${expectA}${expectB}`)));
   145: });

  Value is not `true`:

  false



  index » should support output as (non-previously existent) path

  C:\Users\elydelac\workspace\elycruz\rollup-plugin-sass\test\index.js:161

   160:   t.is(squash(readFileSync(outputOptions.file).toString()), '');
   161:   t.is(squash(readFileSync(outputStylePath).toString()), squash(`${expectA}${expectB}`));
   162:   removeSync(outputStylePath);

  Difference:

  - `body{color:red}body{color:green}
  + `body{color:red}␊



  index » should support output as true

  C:\Users\elydelac\workspace\elycruz\rollup-plugin-sass\test\index.js:178

   177:   t.is(squash(readFileSync(outputOptions.file).toString()), '');
   178:   t.is(squash(readFileSync(outputOptions.file.replace('.js', '.css')).toString()), squash(`${expectA}${expectB}`));
   179:   removeSync(outputOptions.file.replace('.js', '.css'));

  Difference:

  - `body{color:red}body{color:green}
  + `body{color:red}␊
```

**Comment by OKman65** [comment]
Any chance to see this merged soon?

**Comment by elycruz** [comment]
The required change for source maps behavior (from this pull request) have been added to the plugin, in version 1.2.5 - The underlying code had changed a bit since this change was submitted so only the required changes where copied over from this pull request.

Tests for the feature #84 (merged).

Copied changes can be seen here: 
https://github.com/differui/rollup-plugin-sass/blob/926186691968bdb6993f646e9ff8a4c42d27e34b/src/index.ts#L179

**Comment by elycruz** [comment]
@dishuostec If you still want to work on this pull request please re-open it.  Thanks 👍🏽 .

**Pull request closed without merging**
